"""pr_body.py — generate PR description from a JSON release artifact.

Usage: python scripts/pr_body.py <tool_folder_path> <version>
Prints the PR body to stdout.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def generate_pr_body(tool_folder: str, version: str) -> str:
    artifact_path = Path(tool_folder) / f"{version}.json"
    data = json.loads(artifact_path.read_text())

    entry_count = len(data["entries"])
    tag_counts: dict[str, int] = {}
    for e in data["entries"]:
        tag_counts[e["tag"]] = tag_counts.get(e["tag"], 0) + 1
    tag_summary = ", ".join(f"{count} {tag}" for tag, count in tag_counts.items())

    return f"""\
**{version}** — automated release notes generated by Gemini 3.5 Flash

**Summary:** {data["summary"]}

| | |
|---|---|
| **Entries** | {entry_count} ({tag_summary}) |
| **Source** | [{version} GitHub Release]({data["release_url"]}) |

*To correct an entry: edit `data/cortex-catalyst/{version}.json` directly, \
then trigger `workflow_dispatch` with `force_version={version}` to re-render.*
"""


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: python scripts/pr_body.py <tool_folder_path> <version>",
              file=sys.stderr)
        sys.exit(1)
    print(generate_pr_body(sys.argv[1], sys.argv[2]))


if __name__ == "__main__":
    main()
